services:
  - type: web
    name: trackingmore-endpoint
    env: python
    repo: https://github.com/tu_usuario/tu_repositorio
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: AMAZON_CLIENT_ID
        fromGroup: amazon-tracking-env
      - key: AMAZON_CLIENT_SECRET
        fromGroup: amazon-tracking-env
      - key: AMAZON_REFRESH_TOKEN
        fromGroup: amazon-tracking-env
      - key: PORT
        value: 10000
